[package]
name = "guardian"
version = "0.1.1"

description = "Provides owned mutex guards for refcounted mutexes."
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

documentation = "https://jon.tsp.io/crates/guardian"
homepage = "https://github.com/jonhoo/guardian"
repository = "https://github.com/jonhoo/guardian.git"

keywords = ["locks","mutex","synchronization","rc"]

license = "MIT/Apache-2.0"

[dependencies]
